### ISSUE TITLE
2.1: Interim step to click Log in with OpenShift before I get to screen where I can enter my credentials

### ISSUE THREAD

**Issue by guimou** [rh-aiservices-bu/parasol-insurance#87] opened 2024-04-22 15:39 UTC
![image](https://github.com/rh-aiservices-bu/parasol-insurance/assets/3944034/e04fd9f0-94b0-414a-8d8a-7faed4b7e926)

**Comment by erwangranger** [comment] 2024-04-24 21:15
dupe of https://github.com/rh-aiservices-bu/parasol-insurance/issues/90?

**Comment by rcarrata** [comment] 2024-04-25 07:57
agree, seems a dupe of #90

**Closed** 2024-04-26 08:33 UTC
